version: 0.0
os: linux
files:
  - source: /
    destination: /opt/eddyTestCICD
hooks:
  BeforeInstall:
    - location: _scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: _scripts/start_server.sh
      timeout: 300
      runas: ec2-user