version: 0.2
phases:
  # Install Runtime and Dependency
  install:
    runtime-versions:
        nodejs: 16
    commands:
      - echo "======================  codebuild hrmall_admin   ============================="
  # Build
  #pre_build:
  build:
    commands:
      #這時候我們在專案folder裡
      #- yum install p7zip -y
      #- chmod +x _scripts -R
      #- npm config set package-lock false
      - npm install
      #- npm run start
      - echo "project installed..."
      # npm install 的時候, 本機檔案會做成像mount point的樣子, 上傳過程中會被省略
      # 所以這邊用7zip把它變成檔案, 再unzip上傳
      #- 7za a eddyTest.7z ./*
      #- echo $(ls)
      #- 7za x eddyTest.7z -o./eddyTest

artifacts:
  files:
    - '**/*'